# Generated by Django 5.1.4 on 2026-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrecipient",
            name="webhook_url",
            field=models.URLField(
                blank=True,
                help_text="Slack incoming webhook URL (required if channel is SLACK)",
            ),
        ),
    ]
