# Generated by Django 5.1.4 on 2026-08-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alertrecipient_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrecipient",
            name="receive_digest",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this recipient receives the daily digest email",
            ),
        ),
    ]
