# Generated by Django 5.1.4 on 2026-08-06 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheckRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("devices_checked", models.PositiveIntegerField(default=0)),
                ("devices_timed_out", models.PositiveIntegerField(default=0)),
                ("devices_recovered", models.PositiveIntegerField(default=0)),
                ("errors", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceStatusChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("DEGRADED", "Degraded"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("DEGRADED", "Degraded"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("HEARTBEAT_TIMEOUT", "Heartbeat Timeout"),
                            ("HEARTBEAT_RECEIVED", "Heartbeat Received"),
                            ("ERROR_CODES_DETECTED", "Error Codes Detected"),
                            ("ERROR_CODES_CLEARED", "Error Codes Cleared"),
                            ("MANUAL", "Manual Override"),
                            ("SYSTEM_STARTUP", "System Startup"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_status_changes",
                        to="hierarchy.area",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="hierarchy.device",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_status_changes",
                        to="hierarchy.facility",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_status_changes",
                        to="hierarchy.lane",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "changed_at"],
                        name="monitoring__device__bf0b38_idx",
                    ),
                    models.Index(
                        fields=["facility", "changed_at"],
                        name="monitoring__facilit_c73800_idx",
                    ),
                ],
            },
        ),
    ]
