# Generated by Django 5.1.4 on 2026-08-17 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        help_text="Anomaly score 0.0–1.0 — higher means more likely to fail"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Human-readable reason for this risk score"
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_scores",
                        to="hierarchy.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at", "-risk_score"],
                "indexes": [
                    models.Index(
                        fields=["device", "computed_at"],
                        name="monitoring__device__34e7a4_idx",
                    )
                ],
            },
        ),
    ]
