# Generated by Django 5.1.4 on 2026-08-11 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("TRAFFIC_SPIKE", "Traffic Spike"),
                            ("TRAFFIC_DROP", "Traffic Drop"),
                            ("DEVICE_FLAPPING", "Device Flapping"),
                            ("ERROR_RATE", "Abnormal Error Rate"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("observed_value", models.FloatField()),
                ("baseline_value", models.FloatField()),
                ("std_dev", models.FloatField()),
                ("sigma_score", models.FloatField()),
                ("explanation", models.TextField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="hierarchy.facility",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="hierarchy.lane",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["facility", "detected_at"],
                        name="ml_anomaly_facilit_cb83d3_idx",
                    ),
                    models.Index(
                        fields=["lane", "detected_at"],
                        name="ml_anomaly_lane_id_e2d892_idx",
                    ),
                    models.Index(
                        fields=["is_acknowledged", "detected_at"],
                        name="ml_anomaly_is_ackn_061059_idx",
                    ),
                ],
            },
        ),
    ]
