# Generated by Django 5.1.4 on 2026-08-13 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("forecast_for", models.DateTimeField()),
                ("predicted", models.FloatField()),
                ("predicted_low", models.FloatField()),
                ("predicted_high", models.FloatField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="hierarchy.facility",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="hierarchy.lane",
                    ),
                ),
            ],
            options={
                "ordering": ["lane", "forecast_for"],
                "indexes": [
                    models.Index(
                        fields=["lane", "forecast_for"],
                        name="ml_forecast_lane_id_7470cd_idx",
                    ),
                    models.Index(
                        fields=["facility", "forecast_for"],
                        name="ml_forecast_facilit_e3c6fa_idx",
                    ),
                ],
                "unique_together": {("lane", "forecast_for")},
            },
        ),
    ]
