# Generated by Django 5.1.4 on 2026-08-04 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this facility",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. 'Downtown Garage'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique code used in MQTT topics, e.g. 'DG-01'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address of the facility"
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="Total vehicle capacity across all areas"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive facilities are hidden from dashboards",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Local timezone for this facility, e.g. 'Asia/Karachi'",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible key-value store for facility-specific config",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Level 2', 'Zone B', 'Building C'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in MQTT topics, e.g. 'L2'",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="Vehicle capacity for this area"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "facility",
                    models.ForeignKey(
                        help_text="The facility this area belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="hierarchy.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ["facility", "name"],
                "unique_together": {("facility", "code")},
            },
        ),
        migrations.CreateModel(
            name="Lane",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Entry Lane 3', 'Exit Lane 1'", max_length=255
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in MQTT topics, e.g. 'EL-3'",
                        max_length=50,
                    ),
                ),
                (
                    "lane_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry"),
                            ("EXIT", "Exit"),
                            ("PAY", "Pay Station"),
                            ("ENTRY_EXIT", "Bi-directional"),
                        ],
                        default="ENTRY",
                        help_text="Whether vehicles enter, exit, or pay here",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "area",
                    models.ForeignKey(
                        help_text="The area this lane belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanes",
                        to="hierarchy.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lane",
                "verbose_name_plural": "Lanes",
                "ordering": ["area", "name"],
                "unique_together": {("area", "code")},
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Barrier Gate #12', 'LPR Camera #4'",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique device code — used as MQTT client ID",
                        max_length=50,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("BARRIER_GATE", "Barrier Gate"),
                            ("LPR_CAMERA", "LPR Camera"),
                            ("KIOSK", "Payment Kiosk"),
                            ("INTERCOM", "Intercom"),
                            ("TICKET_DISPENSER", "Ticket Dispenser"),
                            ("SENSOR", "Occupancy Sensor"),
                        ],
                        help_text="Determines which health rules apply to this device",
                        max_length=30,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer serial number for maintenance records",
                        max_length=100,
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True,
                        help_text="Current firmware version running on device",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("DEGRADED", "Degraded"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Current health status, updated by heartbeat monitor",
                        max_length=20,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent heartbeat received",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivated devices are excluded from monitoring",
                    ),
                ),
                (
                    "heartbeat_timeout_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Seconds without heartbeat before device is marked offline",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Device-specific config: IP address, port, credentials ref, etc.",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        help_text="The lane this device is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="hierarchy.lane",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["lane", "name"],
                "unique_together": {("lane", "code")},
            },
        ),
    ]
