# Generated by Django 5.1.4 on 2026-08-17 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("REGIONAL_MANAGER", "Regional Manager"),
                            ("FACILITY_OWNER", "Facility Owner"),
                        ],
                        default="FACILITY_OWNER",
                        max_length=20,
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Facilities this user has access to. Ignored for Admin role.",
                        related_name="user_profiles",
                        to="hierarchy.facility",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
