# Generated by Django 5.1.4 on 2026-08-05 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='hierarchy.device')),
                ('facility_code', models.CharField(db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('error_codes', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ingestion_heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_events', to='hierarchy.device')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_events', to='hierarchy.lane')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_events', to='hierarchy.area')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_events', to='hierarchy.facility')),
                ('event_type', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ingestion_vehicle_events',
                'ordering': ['-timestamp'],
            },
        ),
        # Drop UUID-only PK, replace with composite (record_id, timestamp)
        # This is required by TimescaleDB for hypertable partitioning
        migrations.RunSQL(
            sql="""
                ALTER TABLE ingestion_heartbeats
                    DROP CONSTRAINT ingestion_heartbeats_pkey,
                    ADD PRIMARY KEY (record_id, timestamp);
            """,
            reverse_sql="SELECT 1;",
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE ingestion_vehicle_events
                    DROP CONSTRAINT ingestion_vehicle_events_pkey,
                    ADD PRIMARY KEY (record_id, timestamp);
            """,
            reverse_sql="SELECT 1;",
        ),
        # Now convert to hypertables — composite PK includes timestamp ✓
        migrations.RunSQL(
            sql="""
                SELECT create_hypertable(
                    'ingestion_heartbeats',
                    'timestamp',
                    chunk_time_interval => INTERVAL '1 day',
                    if_not_exists => TRUE
                );
            """,
            reverse_sql="SELECT 1;",
        ),
        migrations.RunSQL(
            sql="""
                SELECT create_hypertable(
                    'ingestion_vehicle_events',
                    'timestamp',
                    chunk_time_interval => INTERVAL '1 day',
                    if_not_exists => TRUE
                );
            """,
            reverse_sql="SELECT 1;",
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE ingestion_heartbeats
                SET (
                    timescaledb.compress,
                    timescaledb.compress_orderby = 'timestamp DESC',
                    timescaledb.compress_segmentby = 'facility_code'
                );
            """,
            reverse_sql="SELECT 1;",
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE ingestion_vehicle_events
                SET (
                    timescaledb.compress,
                    timescaledb.compress_orderby = 'timestamp DESC',
                    timescaledb.compress_segmentby = 'facility_id'
                );
            """,
            reverse_sql="SELECT 1;",
        ),
    ]
