# Generated by Django 5.1.4 on 2026-08-04 10:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heartbeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facility_code", models.CharField(db_index=True, max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("error_codes", models.JSONField(default=list)),
                ("metrics", models.JSONField(default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="hierarchy.device",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_heartbeats",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="ingestion_h_device__38fdc9_idx",
                    ),
                    models.Index(
                        fields=["facility_code", "timestamp"],
                        name="ingestion_h_facilit_0f8e6a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VehicleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE_ENTRY", "Vehicle Entry"),
                            ("VEHICLE_EXIT", "Vehicle Exit"),
                            ("PAYMENT_COMPLETED", "Payment Completed"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("BARRIER_OPEN", "Barrier Open"),
                            ("BARRIER_CLOSE", "Barrier Close"),
                            ("FAULT", "Device Fault"),
                            ("RECOVERY", "Device Recovery"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "plate_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_events",
                        to="hierarchy.area",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_events",
                        to="hierarchy.device",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_events",
                        to="hierarchy.facility",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_events",
                        to="hierarchy.lane",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_vehicle_events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="ingestion_v_device__6d277e_idx",
                    ),
                    models.Index(
                        fields=["lane", "timestamp"],
                        name="ingestion_v_lane_id_d40089_idx",
                    ),
                    models.Index(
                        fields=["facility", "timestamp"],
                        name="ingestion_v_facilit_17c553_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="ingestion_v_event_t_102eec_idx",
                    ),
                ],
            },
        ),
    ]
